FROM python:3.11-slim

WORKDIR /app

COPY requirements/requirements-streamlit.txt requirements-streamlit.txt
RUN pip install --no-cache-dir -r requirements-streamlit.txt

COPY shared/ /app/shared/
COPY frontend/streamlit_frontend.py /app/streamlit_frontend.py

EXPOSE 8501

ENV PYTHONPATH=/app

CMD ["streamlit", "run", "streamlit_frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]